### ISSUE TITLE
Translation issues on 404 (not found) route

### ISSUE THREAD

**Issue by cfecherolle** [daaru00/gridsome-plugin-i18n#19]
**Describe the bug**
When reaching a route which does not exist while using a specific language prefix (example: `/en/fake-route`) the route will not be displayed in english (URL prefix language) but in default language.

**To Reproduce**
1. Go to any route that doesn't exist in your Gridsome app, with a language prefix at the beginning of the path
2. The route should be in the prefix language, it's not, it's in the default language which was configured in gridsome-i18n instead.

In `gridsome.client.js`, when entering this kind of non-existing route, in `beforeEach` hook, the value of `to.meta.locale` is always the default language, the prefix is not taken into account => the route is in default language.

**Expected behavior**
The 404 route and template is in the language specified as prefix in the URL.

I haven't found a workaround yet, which is a problem because when a user reaches a non-existing page somehow, it will be shown an error page in French instead of its own language (say, English).

**Comment by daaru00** [comment]
You right, it seems because non matching paths does not have a related Gridsome page, nor a pre-configured route so cannot get current locale from page/route metadata.

Do you have any solution in mind?

IMHO we need to be elaborate the locale directly checking the path segment, something like this:
```javascript
  // Change locale based on route meta tag
  router.beforeEach((to, from, next) => {
    // Change locale
    if ((to.meta && to.meta.locale) && to.meta.locale !== i18n.locale) {
      i18n.locale = to.meta.locale
    }

    // Elaborate locale in not-found routes
    if (to.matched.some(record => record.name === '*')) {
      const langPathSegments = to.path.split('/')
      if (langPathSegments.length > 2) {
        const locale = langPathSegments[1]
        if (options.pathAliases[locale]) {
          i18n.locale = options.pathAliases[locale]
        } else if (options.locales.includes(locale)) {
          i18n.locale = locale
        }
      }
    }
    next()
  })
```
where `to.matched.some(record => record.name === '*')` match the catchall route (aka 404) e split the path into segments. Then check the first path part `/something/` and check if is a valid locale code (or alias).

**Comment by daaru00** [comment]
An other solution, what about pre gerating different 404 using a wildcard path? 

Something like (inside gridsome.server.js):
```javascript
        createPage({
          path: path.join(`/${pathSegment}/`, '*'),
          context: Object.assign({}, page.context, {
            locale:  `${locale}`
          }),
          route:{
            meta: {
              locale:  `${locale}`
            }
          }
        })
```
this will generate, for example, `/en/*`, `/it/*`, `/fr/*` and become a "real page" with locale metadata.

Don't know which component should be related, maybe it need to search the 404 from the current generated routes.

**Comment by giuseppeaiello** [comment]
Hello @daaru00,
  your second solutions looks like the most clean and customizable to me. If you assign:
```js
component: './src/pages/404.vue'
```
and the **locale** is correctly set, it would be easy to manage the localized messages. Given the **page.context**, it's also possible to extend it to further use cases in my opinion...

**Comment by cfecherolle** [comment]
Hi @daaru00, @giuseppeaiello 

I tried a mix of your snippets, but to no avail: pages with URL such as `/{prefix}/unknown-route` are still matched to `*` default pre-existing 404 route.

I pushed a branch named `fix/404_translation` with what I tried (not working), the thing is I can see in Vue pluging for dev console that the new routes are created with path `/{prefix}/*/`, with trailing slash, even though I didn't add one. Maybe this is why it doesn't match? Why is it there? I don't know.

**Comment by daaru00** [comment]
Hi @cfecherolle,

> I tried a mix of your snippets, but to no avail: pages with URL such as /{prefix}/unknown-route are still matched to * default pre-existing 404 route.

yeah, see the same behaviour. 

> I can see in Vue pluging for dev console that the new routes are created with path /{prefix}/*/, with trailing slash, even though I didn't add one

I think is just because page's path will be elaborate with a final slash before creating the route. Noticed the same behaviour also using `createRoute` API:
```
createRoute({ path: `/${pathSegment}/*`, component: './src/pages/404.vue' })
```
still generate `/it/*/`, `/en/*/`. 

I think the problem is here: https://github.com/gridsome/gridsome/blob/e1848132f0466cb4bf2dc0a4bfe621cc9599e1ad/gridsome/lib/pages/pages.js#L330
If I set the type property as dynamic (does not works for createPage):
```
createRoute({ path: `/${pathSegment}/*`, component: './src/pages/404.vue', type: 'dynamic' })
```
it generate routes without the trailing slash:
```
 {
    name: "__it",
    path: "/it/*",
    component: c1,
    meta: {
      dataPath: "/it/*/index.json",
      dynamic: true,
      locale: "it"
    }
  },
```
can this help you?

**Comment by daaru00** [comment]
`createRoute` create route configuration before other routes so `/en/*` will catch all english pages.. 

Maybe I found an other solution, what about using Vue Route syntax to match multiple parameters like the example in doc:
```
var re = pathToRegexp('/:foo+', keys)
// keys = [{ name: 'foo', delimiter: '/', optional: false, repeat: true }]
```
https://github.com/pillarjs/path-to-regexp/tree/v1.7.0#one-or-more

Creating additional pages at the end of `createManagedPages` with something like this:
```js
    for (const locale of this.options.locales) {
      const pathSegment = this.options.pathAliases[locale] || locale
      createPage({
        path: `/${pathSegment}/:slug+`,
        component: './src/pages/404.vue',
        context: {
          locale
        },
        route: {
          meta: {
            locale
          }
        }
      })
    }
```
it should does not match `/en/`, for example, because `+` sign match "one or more" and not "zero or more" like `*` do.

Pages created from files under `src/pages` are generated before that rules so it works with `/en/test` pages. The same for pages like `src/pages/test2/[id].vue`, routes `/en/test2/:id/` are generated before `/en/:slug+` and dynamic pages continue to works.

**Comment by cfecherolle** [comment]
Works like a charm!
Thank you so much for looking into it, I tested this fix locally on my own site with `npm link` and it totally solves the problem!

I've put this new snippet in a commit on `fix/404_translation` branch and will create a pull request.
